name: tsacdop
description: An open source podcast player.

version: 0.6.0+48
publish_to: "none"
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_animated: ^3.0.0
  audio_session: ^0.1.0
  cached_network_image: ^3.1.0
  color_thief_dart: ^0.1.0
  confetti: ^0.6.0
  cupertino_icons: ^1.0.2
  connectivity: ^3.0.3
  crypto: ^3.0.1
  device_info: ^2.0.2
  dio_cookie_manager: ^2.0.0
