name: tsacdop
description: An open source podcast player.

version: 0.6.0+48
publish_to: "none"
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_animated: ^3.0.0
